# -*- coding: utf-8 -*-
"""Final Project ML
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1Sr2VIOGRCJzmlmsQqE25BQoJrt2i3C-w
"""

# Imports
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow import keras
import seaborn as sns

data = pd.read_csv(
    'https://raw.githubusercontent.com/OzymandiasThe2/machine_learning_final_project/main/anime.csv')

# understanding the data
data.head()

# will show all the integer object collumns --> drop this shit
data.describe()

data.shape

# check for columns and rows

data.columns

# checking for unique values

data.nunique()

# cleaning up the data
## Confirm if any null columns
data.isnull().sum()

# dropping values

dataSet = data.drop(columns=["MAL_ID", "English name", "Japanese name", "Aired", "Premiered",
                                "Producers", "Licensors", "Duration", "Members", "Favorites", "Watching",
                                "Completed", "On-Hold", "Dropped", "Plan to Watch",
                                "Score-10", "Score-9", "Score-8", "Score-7", "Score-6", "Score-5",
                                "Score-4", "Score-3", "Score-2", "Score-1"])


dataSet.head()

# shows only Popularity as ints, therefore we have to turn the rest of the int columns into actula intgers
dataSet.describe()

# drop the "unknown" values from the column
drop_score_unknown = dataSet[(dataSet["Score"] == "Unknown")].index
dataSet.drop(drop_score_unknown, inplace=True)

# convert the column from string to integers
dataSet["Score"] = dataSet["Score"].astype(str).astype(float)

# drop the "unknown" values from the column
drop_ranked_unknown = dataSet[(dataSet["Ranked"] == "Unknown")].index
dataSet.drop(drop_ranked_unknown, inplace=True)

# convert the column from string to integers
dataSet["Ranked"] = dataSet["Ranked"].astype(str).astype(float)

# Mamke sure that are columns are prestned right data
dataSet.describe()

# Since the data here is vastly large with 50k entires, we'll compare data points of the top 100 titles and the bottom 100 titles


# TOP 100 from the top
top15 = dataSet.nlargest(15, ['Score'])

# TOP 100 from the bottom
bot15 = dataSet.nsmallest(15, ['Score'])


print("Unique Types of anime = ", dataSet['Type'].unique())
print("\nUnique Genres of anime = ", dataSet["Genres"].unique())
print("\nUnique Rating of anime = ", dataSet["Rating"].unique())

# Checking for outliers > relationship analysis

## Corralation Matrix of the ENTIRE SET,
### SCORE, RANKED, POPULARITY
# corelation = dataSet.corr()
# sns.heatmap(corelation, xticklabels=corelation.columns,yticklabels=corelation.columns, annot = True)

top15.describe()

bot15.describe()

sns.relplot(x = "Ranked", y = "Popularity", hue = "Type", data = dataSet, aspect = 1.5, kind = "line" )

# inverses the y axis and x axis
plt.gca().invert_yaxis()
plt.gca().invert_xaxis()

sns.relplot(x = "Popularity", y = "Score", hue = "Rating", data = dataSet)
plt.gca().invert_xaxis()

sns.relplot(x = "Ranked", y = "Score", hue = "Rating", data = dataSet)
plt.gca().invert_xaxis()

#Plot comparing the ranking and score based on the top 15
sns.relplot(x = "Ranked", y = "Score", hue = "Name", data = top15)
plt.gca().invert_xaxis()

#Same plot comparing the top 15 but with a line of best fit and no legend
sns.lmplot(x = "Ranked", y = "Score", ci = None, data = top15)
plt.gca().invert_xaxis()

#Plot comparing the ranking and score based on the botom 15
sns.relplot(x = "Ranked", y = "Score", hue = "Name", data = bot15)
plt.gca().invert_xaxis()

#Same plot comparing the bottom 15 but with a line of best fit and no legend
sns.lmplot(x = "Ranked", y = "Score", ci = None, data = bot15)
plt.gca().invert_xaxis()
